# Generated by Django 2.0 on 2018-11-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, max_length=64, null=True, verbose_name='Display Name')),
                ('packageName', models.CharField(blank=True, max_length=256, null=True, verbose_name='Package Name')),
            ],
            options={
                'verbose_name': 'My App',
                'verbose_name_plural': 'My Apps',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAppUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=18, verbose_name='UID')),
                ('isUpdated', models.BooleanField(default=False, verbose_name='Is updated')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Apps')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Customer')),
            ],
            options={
                'verbose_name': 'Device App Update',
                'verbose_name_plural': 'Device App Update',
            },
        ),
    ]
